MODEL:
    BACKBONE:
        NAME: 'internimage_b_1k_224'
        CHANNELS: 112
        DEPTHS: [4, 4, 21, 4]
        GROUPS: [7, 14, 28, 56]
        MLP_RATIO: 4.0
        OFFSET_SCALE: 1.0
        NUM_CLASSES: 0
        POST_NORM: True
        DROP_PATH_RATE: 0.4
        LAYER_SCALE: 1.0
        WITH_CP: False
        IN_CHANNELS: [112, 224, 448, 896]
        IMAGE_SIZE: 224
        URL: 'https://huggingface.co/OpenGVLab/InternImage/resolve/main/internimage_b_1k_224.pth'
    BIFPN:
        NAME: 'fpn_5l'
        NUM_CHANNELS: 112
        NUM_LAYERS: 5