MODEL:
    BACKBONE:
        NAME: 'internimage_l_22k_192to384'
        CHANNELS: 160
        DEPTHS: [5, 5, 22, 5]
        GROUPS: [10, 20, 40, 80]
        MLP_RATIO: 4.0
        OFFSET_SCALE: 2.0
        NUM_CLASSES: 0
        POST_NORM: True
        DROP_PATH_RATE: 0.4
        LAYER_SCALE: 1.0
        WITH_CP: False
        IN_CHANNELS: [160, 320, 640, 1280]
        IMAGE_SIZE: 384
        URL: 'https://huggingface.co/OpenGVLab/InternImage/resolve/main/internimage_l_22k_192to384.pth'
    BIFPN:
        NAME: 'fpn_5l'
        NUM_CHANNELS: 112
        NUM_LAYERS: 5