MODEL:
    BACKBONE:
        NAME: 'internimage_xl_22k_192to384'
        CHANNELS: 192
        DEPTHS: [5, 5, 24, 5]
        GROUPS: [12, 24, 48, 96]
        MLP_RATIO: 4.0
        OFFSET_SCALE: 2.0
        NUM_CLASSES: 0
        POST_NORM: True
        DROP_PATH_RATE: 0.4
        LAYER_SCALE: 1.0
        WITH_CP: False
        IN_CHANNELS: [192, 384, 768, 1536]
        IMAGE_SIZE: 384
        URL: 'https://huggingface.co/OpenGVLab/InternImage/resolve/main/internimage_xl_22k_192to384.pth'
    BIFPN:
        NAME: 'fpn_5l'
        NUM_CHANNELS: 256
        NUM_LAYERS: 5