NAME: 'internimage_s'
CHANNELS: 80
DEPTHS: [4, 4, 21, 4]
GROUPS: [5, 10, 20, 40]
MLP_RATIO: 4.0
OFFSET_SCALE: 1.0
NUM_CLASSES: 0
POST_NORM: True
DROP_PATH_RATE: 0.3
LAYER_SCALE: 1.0
WITH_CP: True
IN_CHANNELS: [80, 160, 320, 640]
IMAGE_SIZE: 224
URL: 'https://huggingface.co/OpenGVLab/InternImage/resolve/main/internimage_s_1k_224.pth'
CORE_OP: 'DCNv3'