NAME: 'voc2012'
TRAIN_SET: 'train'
VAL_SET: 'val'
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]
OBJ_LIST: ['__background__', 'aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor']
IMAGE_SIZE: 224